config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "meetups#index"

  resources :meetups do
    resources :comments
  end

  namespace :api, :defaults => { :format => :json } do
    namespace :v1 do
      get "/meetups"  => "meetups#index", :as => :meetups
      post "/signup" => "auth#signup"
      post "/login" => "auth#login"
      post "/logout" => "auth#logout"
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :meetup
  belongs_to :user
end

app/models/meetup.rb
class Meetup < ApplicationRecord
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :comments
  before_create :generate_authentication_token

  def generate_authentication_token
    self.authentication_token = Devise.friendly_token
  end

end

app/controllers/api/v1/auth_controller.rb
class Api::V1::AuthController < ApiController

  before_action :authenticate_user!, :only => [:logout]

  def signup
    user = User.new( :email => params[:email], :password => params[:password] )

    if user.save
      render :json => { :user_id => user.id }
    else
      render :json => { :message => "Failed", :errors => user.errors }, :status => 400
    end
  end

  def login
    if params[:email] && params[:password]
      user = User.find_by_email( params[:email] )
    end

    if user && user.valid_password?( params[:password] )
      render :json => { :message => "Ok",
                        :auth_token => user.authentication_token,
                        :user_id => user.id }
    else
      render :json => { :message => "Email or Password is wrong" }, :status => 401
    end
  end

  def logout
    current_user.generate_authentication_token # 重新产生一组，本来的 token 就失效了
    current_user.save!

    render :json => { :message => "Ok"}
  end

end

app/controllers/api/v1/meetups_controller.rb
class Api::V1::MeetupsController < ApiController

  def index
    @meetups = Meetup.all
    render :json => {
      :data => @meetups.map{ |meetup|
        { :title => meetup.title,
          :description => meetup.description,
          
        }
      }
    }
  end

end

app/controllers/api_controller.rb
class ApiController < ActionController::Base

  before_action :authenticate_user_from_token!

  def authenticate_user_from_token!

    if params[:auth_token].present?
      user = User.find_by_authentication_token( params[:auth_token] )

      # sign_in 是 Devise 的方法，会设定好 current_user
      sign_in(user, store: false) if user
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def new
    @comment = Comment.new
  end

  def create
    @meetup = Meetup.find(params[:meetup_id])

    @comment = Comment.new(comment_params)
    @comment.meetup_id = @meetup.id
    @comment.user_id = current_user.id

    if @comment.save
      redirect_to :back
    else
      render :new
    end
  end

  protected
  def comment_params
    params.require(:comment).permit(:message)
  end

end

app/controllers/meetups_controller.rb
class MeetupsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  
  def index
    @meetups = Meetup.all
  end

  def show
    @meetup = Meetup.find(params[:id])
  end

  def new
    @meetup = Meetup.new
  end

  def edit
    @meetup = Meetup.find(params[:id])
  end

  def create
    @meetup = Meetup.new(meetup_params)

    if @meetup.save
      redirect_to meetups_path
    else
      render :new
    end
  end

  def update
    @meetup = Meetup.find(params[:id])

    if @meetup.update(meetup_params)
      redirect_to meetups_path
    else
      render :edit
    end
  end

  def destroy
    @meetup = Meetup.find(params[:id])
    @meetup.destroy
    redirect_to meetups_path
  end

  private

  def meetup_params
    params.require(:meetup).permit(:title, :description)
  end

end

app/helpers/api/v1/auth_helper.rb
module Api::V1::AuthHelper
end

app/helpers/api/v1/meetups_helper.rb
module Api::V1::MeetupsHelper
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/meetups_helper.rb
module MeetupsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MeetupDemo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
      <%= flash[:notice] %>
    <% end %>

    <% if flash[:alert] %>
      <%= flash[:alert] %>
    <% end %>

    <% if current_user %>
      <%= link_to('登出', destroy_user_session_path, :method => :delete) %>
      <%= link_to('修改密码', edit_registration_path(:user)) %>
    <% else %>
      <%= link_to('注册', new_registration_path(:user)) %> |
      <%= link_to('登入', new_session_path(:user)) %>
    <% end %>
    
    <%= yield %>
  </body>
</html>

app/views/meetups/_comment_form.html.erb
<%= form_for(Comment.new, url: meetup_comments_path(@meetup)) do |f| %>
    <%= f.text_area :message %>
    <%= f.submit "Submit", :disable_with => 'Submiting...' %>
<% end %>

app/views/meetups/edit.html.erb
<div class="col-md-4 col-md-offset-4">
  <h2>编辑Meetup</h2>

  <hr>
  <%= form_for @meetup do |f| %>

  标题
  <%= f.text_field :title %>
  <br>
  叙述
  <br>
  <%= f.text_area :description %>
  <br>

  <%= f.submit "Submit", :disable_with => 'Submiting...' %>
  <% end %>

</div>

app/views/meetups/index.html.erb
<div class="col-md-12">
  <% if current_user %>
    <p>已经登入：你的 API token 是 <code><%= current_user.authentication_token  %></code></p>
  <% else %>
    <p>尚未登入</p>
  <% end %>
   <div class="meetup">
     <%= link_to("New meetup", new_meetup_path, class: "btn btn-primary pull-right") %>
   </div>
   <table class="table table-hover">
     <thead>
       <tr>
         <td>#</td>
         <td>Title</td>
         <td>Description</td>
       </tr>
     </thead>
     <tbody>
       <% @meetups.each do |meetup| %>
         <tr>
           <td>#</td>
           <td><%= link_to(meetup.title, meetup_path(meetup)) %></td>
           <td><%= meetup.description %></td>
           <td>
               <%= link_to("Edit", edit_meetup_path(meetup), class: "btn btn-sm btn-default")%>
               <%= link_to("Delete", meetup_path(meetup),    class: "btn btn-sm btn-default",
                           method: :delete, data: { confirm: "Are you sure?" } )%>
           </td>
         </tr>
       <% end %>
     </tbody>
   </table>
 </div>

app/views/meetups/new.html.erb
<div class="col-md-4 col-md-offset-4">
  <h2>新增meetup</h2>

  <hr>
  <%= form_for @meetup do |f| %>

  标题
  <%= f.text_field :title %>
  <br>
  叙述
  <br>
  <%= f.text_area :description %>
  <br>

  <%= f.submit "Submit", :disable_with => 'Submiting...' %>
  <% end %>

</div>

app/views/meetups/show.html.erb
<div class="col-md-12">
  <div class="meetup">
    <%= link_to("Edit", edit_meetup_path(@meetup), class: "btn btn-primary pull-right")%>
  </div>
  <h2><%= @meetup.title %></h2>
  <p><%= @meetup.description %></p>
</div>

<% if @meetup.comments.empty? %>
   <p> 尚未有人留言 </p>
<% else %>
   <% @floor = 1 %>
    <% @meetup.comments.each do |comment| %>
      <%= @floor %>楼
        <div class="col-md-12">
          <p><%= comment.message %></p>
        </div>
      <% @floor = @floor + 1 %>
     </br>
    <% end%>
<% end %>


 <%= render 'comment_form' %>